#!/bin/bash

set -ex

scripts=( \
    "01-conditional-power-and-friends.R" \
    "02-naive-recalculation-and-optimal-design.R" \
    "03-application-example.R" \
)

for script in ${scripts[@]};
do
    Rscript -e "source('R/$script')"
done

cp -r output/figures/. latex/figures/

Rscript -e "setwd('latex'); tinytex::install_tinytex(); tinytex::pdflatex('manuscript.tex', pdf_file = '../output/manuscript.pdf')"
