#!/bin/bash

set -ex

echo "source('renv/activate.R')" > .Rprofile

Rscript -e "renv::restore()"

scripts=( \
    "01-conditional-power-and-friends.R" \
    "02-naive-recalculation-and-optimal-design.R" \
    "03-application-example.R" \
)

for script in ${scripts[@]};
do
    Rscript -e "source('R/$script')"
done

cp -r output/figures/. latex/figures/

Rscript -e "tinytex::install_tinytex()"
Rscript -e "setwd('latex'); tinytex::pdflatex('manuscript.tex', pdf_file = '../output/manuscript.pdf')"

echo "# source('renv/activate.R')" > .Rprofile
