name: run

on:
  push:
  pull_request:

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: setup R
      uses: r-lib/actions/setup-r@v1
      with: r-version: '4.0.3'
    - name: cache renv packages
      uses: actions/cache@v1
      with:
        path: $HOME/.local/share/renv
        key: r-${{ hashFiles('renv.lock') }}
        restore-keys: r-
    - name: install packages
      run: |
        sudo apt-get install libcurl4-openssl-dev
        echo "source('renv/activate.R')" > .Rprofile
        R -e 'renv::restore()'
        echo "# source('renv/activate.R')" > .Rprofile
    - run: ./run
